---
# tasks file for singleurl
- name: get k3s version
  shell: k3s --version
  ignore_errors: yes
  register: k3s_version
# block to avoid writing when
- name: install k3s
  when: k3s_version is failed
  block:
# create dir for k3s config
    - name: create dir
      ansible.builtin.file:
        path: /etc/rancher/k3s
        state: directory
        mode: '0755'
# copy k3s config from templates
    - name: copy k3s config
      template:
        src: templates/config.j2
        dest: /etc/rancher/k3s/config.yaml
        mode: '0755'
# main command to install you should to work with the template file 
    - name: install k3s
      shell: curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server" sh -s -
# copy kubeconfig to your host
# you can change the path k3s.yaml
# default where does the playbook start from
    - name: save kubeconfig
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ k3s_yaml_path }}"
        flat: yes
    
    - name: save token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: node_token

# - debug:
#     msg: "test {{ node_token.stdout }}"
# - debug:
#     msg: "{{ tokentest }}"